#change running port
server:
  port: 8080

#h2 database
#spring:
#  datasource:
#    username: vp_innovations_labs
#    url: jdbc:h2:mem:test_db
#    driverClassName: org.h2.Driver
#    password: vp_innovations_2023
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

#MySQL database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test_db
    password: Lakindu@MySQL
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update